name: Examples

on:
  workflow_dispatch:      # Manually start a workflow
  push:
    paths-ignore:
    - '.github/**'        # Ignore changes towards the .github directory
    - '**.md'             # Do no build if *.md files changes

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-12]
        example:
          - "examples/arduino-ble5-advertising"
          - "examples/arduino-blink"
          - "examples/arduino-rmt-blink"
          - "examples/arduino-usb-keyboard"
          - "examples/arduino-wifiscan"
          - "examples/espidf-arduino-blink"
          - "examples/espidf-arduino-wifiscan"
          - "examples/espidf-blink"
          - "examples/espidf-aws-iot"
          - "examples/espidf-ble-eddystone"
          - "examples/espidf-coap-server"
          - "examples/espidf-exceptions"
          - "examples/espidf-hello-world"
          - "examples/espidf-http-request"
          - "examples/espidf-peripherals-uart"
          - "examples/espidf-peripherals-usb"
          - "examples/espidf-storage-sdcard"
          - "examples/espidf-ulp"
          - "examples/espidf-ulp-riscv"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}
